### ISSUE TITLE
The tag id highlighting doesn't work as expected

### ISSUE THREAD

**Issue by tilap35173** [ghaschel/vscode-angular-pug#2]
Hi, I have downloaded your vscode extensions and like as the title said, the tag id highlighting doesn't work as expected.

I have the **Dark+** theme and the tag id is not the same color than your readme.
![image](https://user-images.githubusercontent.com/8711027/51045805-7db60480-1592-11e9-9b42-36a8834c7db0.png)

**Comment by ghaschel** [comment]
Weirdly it works here. Would you mind sharing a bit more of the code you're working on? And also if you're using any other pug extension that may help me replicate your workspace aswell

![screen shot 2019-01-11 at 19 13 56](https://user-images.githubusercontent.com/5878866/51059967-1bcabe80-15d5-11e9-9cb0-41f4846a6bdd.png)

**Comment by tilap35173** [comment]
Yeah, it's a weirdly one here. I have test this case on another PC with similar configurations and I have the same result.
![image](https://user-images.githubusercontent.com/8711027/51087066-39ef0680-171c-11e9-96fc-02efb0af2458.png)

I have testing this case with all the extensions disabled, except **vscode-angular-pug**. It's certainly with my vscode settings. If you want, I can send you my settings for investigating this case.

**Comment by tilap35173** [comment]
I have installed the vscode insiders with no settings and only with your extension and I have the same results. It's just a hypothesis, but it's maybe in your settings or maybe it's my theme that's not working as expected.

**Comment by tilap35173** [comment]
After some research, it's my fault. I was thinking that you use **`dark + (default)`** theme, but you use another theme. After the installation of the theme, the highlighting work as expected.

Sorry about this issue, I will close it.
