### ISSUE TITLE
Highlight breaks when using backquote

### ISSUE THREAD

**Issue by mark-akturatech** [ghaschel/vscode-angular-pug#5]
Hello,
First of all - thank you! Your plugin makes pug files a lot easier to read. 

I have a small issue when using the backquote (`) to split property bindings over multiple lines. The highlighter appears to register a closing bracket with the backquoted string as a pug attribute closing bracket and therefore all following syntax is not correctly highlighted.

Please see this screenshot for an example of the failed syntax highlights:

![image](https://user-images.githubusercontent.com/13212506/84606861-b0350100-aeec-11ea-85a1-a1bbf58d0cb3.png)

**Comment by mark-akturatech** [comment]
Hello,
I just found another file not rendering properly. Thinking now it is not related to backquote.
See below, it has incorrect colouring after `nav.wrapper(middle, #wizardContainer)` line.

![image](https://user-images.githubusercontent.com/13212506/84609594-f42f0280-aefa-11ea-9ba6-7f9b717ac3e2.png)

**Comment by ghaschel** [comment]
Can you share these snippets in text? I will work directly on them to simulate the error =]

**Comment by mark-akturatech** [comment]
Oh of course. Sorry, silly of me not to think about doing that in the first place.

```
section.section-auth
  .sign-up-container
    h1 {{ "Content Snare" }}

    //- left column
    .sign-up-row
      .sign-up-col.left
        h2 {{ "Content Snare" | translate }}
        h3 {{ "Get Content From Your Clients On Time" | translate: null:"":"Heading" }}

        cs-testimonial-slider

        p.login
          span.
            {{ "Already a member?" | translate: null:"":"Subheading" }}
            &nbsp;
          a(routerLink='/auth/sign-in') {{ "Log in to your account" | translate: null:"":"Anchor" }}

      //- right column
      .sign-up-col.right(role='main')
        .alert(
          *ngIf='serverResponse',
          role='alert',
          [innerHtml]=`
            serverResponse === ServerResponse.genericError 
              ? ("<p><strong>Oh no... something went skew-whiff :(</strong></p><p>Please try again later or contact our support team by pressing the <i>cant access your account?</i> link on the sign in button</p></div>" | translate)
              : ("<p><strong>We can't access your Internet :(</strong></p><p>Please ensure you are connected and try again.</p>" | translate)`
        )

        //- signup pages
        ng-container([ngSwitch]='step')
          cs-sign-up-details(
            *ngSwitchCase='SignUpSteps.signUpInfo',
            [form]='signUpForm',
            (next)='onStep(SignUpSteps.personalInfo)'
          )
          cs-personal-details(
            *ngSwitchCase='SignUpSteps.personalInfo',
            [form]='signUpForm',
            (next)='onStep(SignUpSteps.companyInfo)'
          )
          cs-new-company-details(
            *ngSwitchCase='SignUpSteps.companyInfo',
            [form]='signUpForm',
            [isDisabled]='isDisabled',
            (next)='onSignUpComplete()'
          )

        p.mobile-sign-up
          span {{ "Already a member?" | translate: null:"":"Subheading" }}&nbsp;
          a(routerLink='/auth/sign-in') {{ "Sign in to your account" | translate: null:"":"Anchor" }}
```
and...

```
cs-toolbar(
  [hasSaveButtons]='false',
  [displayPageTitle]='false',
  [actionItems]='ACTION_OPTIONS',
  [hideActionItems]='true',
  (dropDownOpen)='onDropDownOpen($event)',
  (action)='onSetStep($event)'
)
  div(return)
    button.cs-button.return(*ngIf='previousStep === RequestWizardStep.home', routerLink='/').
      {{ previousStepText || '' | translate }}
    button.cs-button.return(
      *ngIf='!customReturn && previousStep !== RequestWizardStep.home',
      (click)='onSetStep(previousStep)'
    ) {{ previousStepText || "" | translate }}
    ng-content(*ngIf='customReturn')

  nav.wrapper(middle, #wizardContainer)
    .selected(*ngIf='!isWizardVisible') {{ currentStepText || "" | translate }}

    ul(*ngIf='isWizardVisible', role='listbox', aria-label='Edit request wizard steps')
      ng-container(*ngFor='let step of ACTION_OPTIONS; trackBy: trackByFunction')
        li(
          *ngIf='!step.hidden',
          role='option',
          [ngClass]=`{
            selected: currentStep === step.id,
            allowed: (step.id || 0) <= maxAllowedStep
          }`
        )
          span.step((click)='onSetStep(step.id)') {{ step?.text || "" | translate }}
          span.icon.cs-icon-right
```

**Comment by ghaschel** [comment]
There are actually three bugs that I could found. One of them is related to ``` not capturing angular interpolations and angular expressions and this I managed to fix already.

But there are two more I'm trying to kill. One of them is related to a new line being mandatory to detect angular interpolations:
![image](https://user-images.githubusercontent.com/5878866/84777612-2f433b80-afb8-11ea-91c3-de673eb13a64.png)

and the other one is `=` being mandatory after an angular directive starter for it to being detected.
![image](https://user-images.githubusercontent.com/5878866/84777719-57cb3580-afb8-11ea-8504-72950721bcc2.png)
![image](https://user-images.githubusercontent.com/5878866/84777730-5ac62600-afb8-11ea-8664-8d11a70c612b.png)

I hope to fix this untill the end of the day. Let me know if you find any other one! Thanks for reporting it =]

**Comment by mark-akturatech** [comment]
@ghaschel 
Thank you. But don't rush. It isn't urgent or anything. I just reported the bug as I really enjoy your add-on and thought it was worth reporting to you.
If there is anything I can do to help test, please let me know.

**Comment by ghaschel** [comment]
Fixed it in [0.3.1](https://github.com/ghaschel/vscode-angular-pug/commit/a7b8e0575fdd6b66e39c4d505d226185027a00d5).

I will open another issue with the pending bug I didn't have the proper time yet to look into. You can follow it [here](https://github.com/ghaschel/vscode-angular-pug/issues/6)

**Comment by ghaschel** [comment]
Please, let me know if this issue is fixed to you.

**Comment by mark-akturatech** [comment]
@ghaschel Subscribed to the new issue.

Thank you mate. I installed the new version and so far it looks great. I'll let you know in the new bug if I find any specific broken instances.

Thank you again. I appreciate your efforts a lot.
